"""added category to video

Revision ID: 8eab067cd6d6
Revises: 3f1fd9ba7ff2
Create Date: 2024-11-15 05:22:43.596662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eab067cd6d6'
down_revision = '3f1fd9ba7ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
