"""made video-ref nullable

Revision ID: bc2ea9051403
Revises: 4bd57df06b09
Create Date: 2024-10-27 06:24:11.802126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2ea9051403'
down_revision = '4bd57df06b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_click', sa.DateTime(), nullable=False))
        batch_op.alter_column('video_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_created_at')
        batch_op.drop_index('ix_user_point')
        batch_op.drop_index('ix_user_point_created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_point_created_at', ['point', 'created_at'], unique=False)
        batch_op.create_index('ix_user_point', ['point'], unique=False)
        batch_op.create_index('ix_user_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.alter_column('video_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('last_click')

    # ### end Alembic commands ###
