"""removed points from video

Revision ID: f9752d918eca
Revises: 9d7193e04ff6
Create Date: 2024-10-09 13:57:49.959745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9752d918eca'
down_revision = '9d7193e04ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('point')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
