"""removed public link

Revision ID: 20324deb3730
Revises: 863bd5ac0241
Create Date: 2024-10-01 20:39:17.570343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20324deb3730'
down_revision = '863bd5ac0241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_videos_public_url', type_='unique')
        batch_op.drop_column('public_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('uq_videos_public_url', ['public_url'])

    # ### end Alembic commands ###
