"""add platform

Revision ID: 863bd5ac0241
Revises: 8009af6cd529
Create Date: 2024-10-01 17:24:26.349900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863bd5ac0241'
down_revision = '8009af6cd529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
